[package]
name = "clipd"
version = "0.1.0"
edition = "2021"

[dependencies]
clipto-ipc = { path = "../clipto-ipc" }
chacha20poly1305 = "0.10"
zeroize = { version = "1", features = ["derive"] }
rand = "0.8"
anyhow = "1"
ctrlc = "3"
inotify = "0.10"
